In [1]:
import numpy as np



In [2]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with Rank 2: \n", arr)

Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]


In [8]:
np.empty([2, 2])

array([[2.33643959e-307, 2.44771536e-307],
       [3.44900369e-307, 4.22792214e-307]])

In [9]:
z = np.copy(arr)
print(z)

[[1 2 3]
 [4 5 6]]


In [10]:
a = ([1,2,3], [4,5,6]) 
np.empty_like(a)

array([[6029427, 7667792, 7077986],
       [6488169, 5439488, 5439557]])

In [11]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [12]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)


array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [13]:
np.linspace(2.0, 3.0, num=5, endpoint=False)


array([2. , 2.2, 2.4, 2.6, 2.8])

In [14]:
np.mgrid[0:5,0:5]


array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [15]:
s = (2,2)
np.zeros(s)

array([[0., 0.],
       [0., 0.]])

In [16]:
y = np.arange(3, dtype=float)
y

array([0., 1., 2.])

In [17]:
np.zeros_like(y)


array([0., 0., 0.])

In [18]:
x = np.array([1, 2, 2.5])
x.astype(int)


array([1, 2, 2])

In [19]:
x = np.arange(9.0).reshape(3,3)
np.atleast_1d(x)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [20]:
x = np.arange(8.0)
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

In [21]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.column_stack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [22]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
a = np.arange(4).reshape(2,2)
a.diagonal()


array([0, 3])

In [24]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.hstack((a,b))

array([1, 2, 3, 2, 3, 4])

In [25]:
x = np.array([[1,2],[3,4]])
np.repeat(x, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [26]:
x = np.array([[[0], [1], [2]]])
x.shape
np.squeeze(x, axis=0).shape


(3, 1)

In [27]:
x = np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [28]:
np.all([[True,False],[True,True]])


False

In [31]:
a = np.arange(6).reshape(2,3) + 10
np.argmin(a)


0

In [32]:
np.argmax(a)


5

In [33]:
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0], dtype=int64)

In [34]:
np.searchsorted([1,2,3,4,5], 3, side='right')


3

In [35]:
a = np.array([[1, 2], [3, 4], [5, 6]])
np.compress([0, 1], a, axis=0)


array([[3, 4]])

In [36]:
a = np.array([1,2,3])
np.cumprod(a)

array([1, 2, 6], dtype=int32)

In [37]:
a = np.array([[1,2,3], [4,5,6]])
np.cumsum(a)


array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [38]:
a = np.array([1,2,3])
b = np.array([0,1,0])
np.inner(a, b)

2

In [39]:
a = np.array([1, 2])
a.fill(0)
a

array([0, 0])

In [40]:
a = np.array([[1,4],[3,1]])
np.sort(a)

array([[1, 4],
       [1, 3]])

In [41]:
x = np.arange(6).reshape(2, 3)
np.putmask(x, x>2, x**2)
x

array([[ 0,  1,  2],
       [ 9, 16, 25]])

In [42]:
a = np.arange(5)
np.put(a, [0, 2], [-44, -55])
a

array([-44,   1, -55,   3,   4])

In [43]:
a = np.array([1+2j, 3+4j, 5+6j])
a.real

array([1., 3., 5.])

In [44]:
np.sum([0.5, 1.5])

2.0

In [45]:
x = [1, 2, 3]
y = [4, 5, 6]
np.cross(x, y)

array([-3,  6, -3])

In [46]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [47]:
rl = np.outer(np.ones((5,)), np.linspace(-2, 2, 5))
rl

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

In [48]:
a = np.array([[1, 2], [3, 4]])
np.mean(a)

2.5

In [49]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [51]:
x = np.arange(3.0)
np.atleast_2d(x)


array([[0., 1., 2.]])

In [52]:
np.atleast_2d(1, [1, 2], [[1, 2]])


[array([[1]]), array([[1, 2]]), array([[1, 2]])]

In [53]:
x = np.array([[1, 2], [3, 4]])
m = np.asmatrix(x)
m

matrix([[1, 2],
        [3, 4]])

In [54]:
x = np.array([[4, 9, 2, 10],
              [6, 9, 7, 12]])
np.ptp(x, axis=1)


array([8, 6])

In [55]:
a = np.array([1+2j, 3+4j, 5+6j])
a.imag

array([2., 4., 6.])

In [56]:
a = np.arange(5)
np.put(a, [0, 2], [-44, -55])
a

array([-44,   1, -55,   3,   4])

In [57]:
x = np.arange(6).reshape(2, 3)
np.putmask(x, x>2, x**2)
x

array([[ 0,  1,  2],
       [ 9, 16, 25]])

In [58]:
a = np.array([[1, 2], [3, 4]])
np.std(a)

1.118033988749895

In [59]:
a = np.array([[1, 2], [3, 4]])
np.var(a)

1.25